name: expressjs_interop
description: Dart bindings and interop layer for ExpressJS.
version: 0.0.3
homepage: https://github.com/pulyaevskiy/expressjs-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  js: ^0.6.1
  node_interop: ^1.0.0-dev
  node_http: ^1.0.0-dev

dev_dependencies:
  test: ^1.0.0
  build_runner: ^0.9.1
  build_node_compilers: ^0.1.8
  build_test: