name: expressjs_interop
description: Dart bindings and interop layer for ExpressJS.
version: 0.0.1
homepage: https://github.com/pulyaevskiy/expressjs-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: ^0.6.1
  node_interop: ^0.0.7

dev_dependencies:
  test: ^0.12.0

transformers:
  - $dart2js
  - node_interop:
      include: "**/*.dart.js"
